name: AWS Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'phase1-iac/terraform/aws/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'phase1-iac/terraform/aws/**'

jobs:
  terraform:
    name: Terraform AWS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: phase1-iac/terraform/aws
      run: terraform init

    - name: Terraform Plan
      working-directory: phase1-iac/terraform/aws
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
